export const COLOR_SCHEDULE_ITEM_PENDING = '#C7C979';
export const COLOR_SCHEDULE_ITEM_FILLED = '#7BC979';
export const COLOR_SCHEDULE_PROGRESS_BACKGROUND = '#385682';
export const COLOR_SCHEDULE_PROGRESS_BAR = '#5297FF';
